/** @type {import('tailwindcss').Config} */
const colorVar = (name) => `rgb(var(--${name}) / <alpha-value>)`

module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}', './index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-tint": colorVar('surface-tint'),
        "on-background": colorVar('on-background'),
        "secondary": colorVar('secondary'),
        "error": colorVar('error'),
        "on-primary-container": colorVar('on-primary-container'),
        "tertiary-fixed-dim": colorVar('tertiary-fixed-dim'),
        "surface-dim": colorVar('surface-dim'),
        "surface-container-lowest": colorVar('surface-container-lowest'),
        "on-secondary": colorVar('on-secondary'),
        "primary-fixed-dim": colorVar('primary-fixed-dim'),
        "on-tertiary-container": colorVar('on-tertiary-container'),
        "inverse-surface": colorVar('inverse-surface'),
        "on-primary-fixed-variant": colorVar('on-primary-fixed-variant'),
        "secondary-fixed-dim": colorVar('secondary-fixed-dim'),
        "surface-container-low": colorVar('surface-container-low'),
        "error-container": colorVar('error-container'),
        "primary-container": colorVar('primary-container'),
        "outline-variant": colorVar('outline-variant'),
        "on-secondary-fixed-variant": colorVar('on-secondary-fixed-variant'),
        "surface-container-highest": colorVar('surface-container-highest'),
        "on-surface-variant": colorVar('on-surface-variant'),
        "surface-container": colorVar('surface-container'),
        "background": colorVar('background'),
        "primary-fixed": colorVar('primary-fixed'),
        "on-surface": colorVar('on-surface'),
        "on-tertiary-fixed": colorVar('on-tertiary-fixed'),
        "surface-container-high": colorVar('surface-container-high'),
        "inverse-primary": colorVar('inverse-primary'),
        "primary": colorVar('primary'),
        "tertiary": colorVar('tertiary'),
        "on-secondary-fixed": colorVar('on-secondary-fixed'),
        "secondary-container": colorVar('secondary-container'),
        "tertiary-container": colorVar('tertiary-container'),
        "on-error-container": colorVar('on-error-container'),
        "on-primary-fixed": colorVar('on-primary-fixed'),
        "surface": colorVar('surface'),
        "on-tertiary": colorVar('on-tertiary'),
        "on-error": colorVar('on-error'),
        "surface-variant": colorVar('surface-variant'),
        "secondary-fixed": colorVar('secondary-fixed'),
        "outline": colorVar('outline'),
        "on-primary": colorVar('on-primary'),
        "on-tertiary-fixed-variant": colorVar('on-tertiary-fixed-variant'),
        "tertiary-fixed": colorVar('tertiary-fixed'),
        "on-secondary-container": colorVar('on-secondary-container'),
        "surface-bright": colorVar('surface-bright'),
        "inverse-on-surface": colorVar('inverse-on-surface'),
      },
      fontFamily: {
        headline: ['Space Grotesk'],
        body: ['Manrope'],
        label: ['Inter'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  daisyui: {
    themes: [
      {
        algodark: {
          primary: '#00FFA3',
          'primary-content': '#003920',
          secondary: '#bcc7de',
          'secondary-content': '#e0e2ea',
          accent: '#00e290',
          'accent-content': '#003920',
          neutral: '#1c2025',
          'neutral-content': '#e0e2ea',
          'base-100': '#101419',
          'base-200': '#181c21',
          'base-300': '#262a30',
          'base-content': '#e0e2ea',
          info: '#00FFA3',
          success: '#00FFA3',
          warning: '#fbbf24',
          error: '#ffb4ab',
        },
      },
      {
        algolight: {
          primary: '#006d43',
          'primary-content': '#ffffff',
          secondary: '#3e495d',
          'secondary-content': '#ffffff',
          accent: '#00e290',
          'accent-content': '#003920',
          neutral: '#eef2f7',
          'neutral-content': '#1c2025',
          'base-100': '#f7f9fc',
          'base-200': '#edf2f7',
          'base-300': '#e2e8f0',
          'base-content': '#1c2025',
          info: '#006d43',
          success: '#047857',
          warning: '#d97706',
          error: '#b91c1c',
        },
      },
    ],
    logs: false,
  },
  plugins: [require('daisyui')],
}
